In [2]:
from skmultiflow.data import ConceptDriftStream
from skmultiflow.data.sea_generator import SEAGenerator
from skmultiflow.data.led_generator_drift import LEDGeneratorDrift
import numpy as np
import pandas as pd

In [2]:
sea_g2_stream = ConceptDriftStream(stream=SEAGenerator
                                   (classification_function=1, 
                                    random_state=None, balance_classes=False, 
                                    noise_percentage=0.39), 
                   drift_stream=SEAGenerator(classification_function=3, 
                                    random_state=None, balance_classes=False, 
                                    noise_percentage=0.39),
                                   position=5000, width=1000, random_state=None)

stream = sea_g2_stream.next_sample(100000)
sea_g2 = pd.DataFrame(np.column_stack(stream),columns=['att_num_0', 'att_num_1', 'att_num_2', 'target_0'])
sea_g2.to_csv('sea_g2.csv')

In [3]:
sea_g3_stream = ConceptDriftStream(stream=SEAGenerator
                                   (classification_function=1, 
                                    random_state=None, balance_classes=False, 
                                    noise_percentage=0.59), 
                   drift_stream=SEAGenerator(classification_function=3, 
                                    random_state=None, balance_classes=False, 
                                    noise_percentage=0.59),
                                   position=5000, width=1000, random_state=None)

stream = sea_g3_stream.next_sample(100000)
sea_g3 = pd.DataFrame(np.column_stack(stream),columns=['att_num_0', 'att_num_1', 'att_num_2', 'target_0'])
sea_g3.to_csv('sea_g3.csv')

In [6]:
led_g2_stream = LEDGeneratorDrift(random_state = 112, noise_percentage = 0.35,has_noise= True,
n_drift_features=2) #es werden 2 Features mit irrelevanten getauscht

stream = led_g2_stream.next_sample(100000)
led_g2_stream = pd.DataFrame(np.column_stack(stream))
led_g2_stream.to_csv('led_g2.csv')

In [3]:
led_g1_stream = LEDGeneratorDrift(random_state = 112, noise_percentage = 0.10,has_noise= True,
n_drift_features=1)

stream = led_g1_stream.next_sample(100000)
led_g1_stream = pd.DataFrame(np.column_stack(stream))
led_g1_stream = led_g1_stream.astype(int)

led_g1_stream.to_csv('led_g1.csv')
led_g1_stream

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,0,1,1,1,0,1,0,0,1,0,...,1,1,0,0,1,1,0,1,1,4
1,0,0,1,0,1,0,0,1,0,0,...,0,1,1,0,0,0,0,1,1,1
2,1,1,1,0,0,1,1,1,1,0,...,1,1,1,1,0,1,0,1,0,0
3,1,0,1,0,0,1,1,1,0,0,...,0,0,1,0,1,1,1,1,1,7
4,1,1,0,0,1,1,1,1,0,1,...,0,1,1,0,0,0,0,1,0,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,0,1,1,1,0,1,0,1,0,1,...,0,0,0,0,0,1,1,0,1,4
99996,1,1,1,1,0,1,1,0,1,1,...,1,1,1,0,1,0,1,1,1,9
99997,1,0,1,1,0,1,1,1,0,1,...,1,1,1,0,1,0,1,0,0,3
99998,1,0,1,1,0,0,1,1,0,1,...,1,0,1,1,1,1,0,1,1,2
99999,1,0,1,0,1,1,0,1,0,1,...,0,1,0,0,0,1,1,0,0,7

In [4]:
import pandas as pd

#df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
df = pd.read_csv('led_g1.csv', index_col=0, names=['att_1', 'att_2', 'att_3', 'att_4', 'att_5',
                                                     'att_6', 'att_7', 'att_8', 'att_9', 'att_10',
                                                     'att_11', 'att_12', 'att_13', 'att_14', 'att_15',
                                                     'att_16', 'att_17', 'att_18', 'att_19', 'att_20',
                                                     'att_21', 'att_22', 'att_23', 'att_24', 'class'])

df = df.iloc[1: , :]
df.to_csv('led_g1.csv')